export const ADD_ROW_INVOICE = 'ADD_ROW_INVOICE';
export const DELETE_ROW_INVOICE = 'DELETE_ROW_INVOICE';
export const UPDATE_FIELD_INVOICE = 'UPDATE_FIELD_INVOICE';
export const GET_ALL_ROWS_INVOICE = 'GET_ALL_ROWS_INVOICE';
export const UPDATE_INVOICE_HEADER = 'UPDATE_INVOICE_HEADER';
// export const SET_INTIAL_STATE = 'SET_INTIAL_STATE';